sudo: false

language: go

services:
  - docker

# Whenever the Go version is updated here, .circleci/config.yml and .promu.yml
# should also be updated.
go:
- 1.11.x

go_import_path: github.com/prometheus/blackbox_exporter

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
- make
- git diff --exit-code

after_success:
  - docker build -t blackbox_exporter .
  - docker tag blackbox_exporter jeffryadityatama/blackbox_exporter:latest
  - docker push jeffryadityatama/blackbox_exporter:latest
